language: python

services:
  - docker

install:
  - pip install coveralls
  - docker build -t otto-engine .
  - mkdir $TRAVIS_BUILD_DIR/config

script: 
  - docker run --rm -e PYTEST_ADDOPTS="--color=yes" -v $TRAVIS_BUILD_DIR/config:/config otto-engine bash -c "cd /config; /app/tests/run_tests.sh"

after_script:
  - cd $TRAVIS_BUILD_DIR/config && coveralls
  - ls -la $TRAVIS_BUILD_DIR
  - ls -la $TRAVIS_BUILD_DIR/config
  - cat $TRAVIS_BUILD_DIR/config/run_otto.log
