language: python
python: 3.7

services:
  - docker

install:
  # - pip install coveralls
  - docker build -t otto-engine .
  # - mkdir $TRAVIS_BUILD_DIR/config

script: 
  - docker run --rm otto-engine bash -c "pytest -v --color=yes --cov=ottoengine /app/tests/unit"
  # - docker run -d >-
  #     --name otto-engine
  #     -e PYTEST_ADDOPTS="--color=yes"
  #     otto-engine
  #     /app/run_otto.py
  # - sleep 1
  # - docker exec -it >-
  #     -e PYTEST_ADDOPTS="--color=yes"
  #     otto-engine
  #     bash -c "pytest -v /app/tests/integration"
  # - docker stop otto-engine
      

after_script:
  # - cd $TRAVIS_BUILD_DIR/config && coveralls
  # - ls -la $TRAVIS_BUILD_DIR
  # - ls -la $TRAVIS_BUILD_DIR/config
  # - cat $TRAVIS_BUILD_DIR/config/run_otto.log
  - docker logs otto-engine