language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config.ini.example config.ini

script: 
  - python run_otto.py test &> otto_engine.log &
  - sleep 5 # Wait for otto-engine to connect to the TestWebSocketServer
  - pytest -v --cov=ottoengine tests/
  - pkill -9 -f run_otto.py

after_script:
  - coveralls
  - cat otto_engine.log
