language: python
python: 3.7

services:
  - docker

install:
  - docker build -t otto-engine .

script: 
  - docker run --rm -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" otto-engine bash -c "pytest -v --cov=ottoengine /app/tests/unit; coveralls"
  - docker run -d --name otto-engine -e PYTEST_ADDOPTS="--color=yes" otto-engine /app/run_otto.py test
  - sleep 1
  - docker exec -it otto-engine pytest -v --color=yes /app/tests/integration
  - docker stop otto-engine
      

after_script:
  - docker logs otto-engine